// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;
import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;

import  simbad.sim.*;
import RootElement.ClassDiagram.Package1.Robot;

/************************************************************/
/**
 * 
 */
public class Robot_Camera extends Robot {
	CameraSensor camera;
	
	public Robot_Camera (Vector3d position, String name) {     
        super(position,name);
        camera = RobotFactory.addCameraSensor(this); 
        setCanBeTraversed(false);
    }
	
	 public void initBehavior() {
		 super.initBehavior();
	 }
	    
	    public void performBehavior() {
	    	super.performBehavior();
	    	if(!collisionDetected()) {
	        	setColor(new Color3f(0,0,0));
	            
	        }
	    }
	    
}

