// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

import RootElement.ClassDiagram.Package1.Robot_Bumper;
import RootElement.ClassDiagram.Package1.Robot_Camera;
import RootElement.ClassDiagram.Package1.Robot_Picker;

/************************************************************/
/**
 * 
 */
public class Coordinate {
	/**
	 * 
	 */
	public int x ;
	/**
	 * 
	 */
	public int y;
	/**
	 * 
	 */
	public int z;
	/**
	 * 
	 */
	public Robot_Bumper robot_bumper;
	/**
	 * 
	 */
	public Robot_Camera robot_camera;
	/**
	 * 
	 */
	public Robot_Picker robot_picker;
};
