// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

/************************************************************/
/**
 * 
 */
public class Environment {
	/**
	 * 
	 */
	public static RootElement.ClassDiagram.Integer World_size = 25;

	/**
	 * 
	 */
	public void Environment() {
	}
};
