// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

import RootElement.ClassDiagram.Package1.Environment;
import RootElement.ClassDiagram.Package1.Robot;

/************************************************************/
/**
 * 
 */
public class Main {
	/**
	 * 
	 */
	public Robot robot;
	/**
	 * 
	 */
	public Environment environment;

	/**
	 * 
	 * @param args 
	 */
	public void Main(RootElement.ClassDiagram.String args) {
	}
};
