// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

/************************************************************/
/**
 * 
 */
import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;
import  simbad.sim.*;

public class Robot extends Agent {
	private double velocity = 0.5;
	private Vector3d origin;
	
	public Robot (Vector3d position, String name) {     
        super(position,name);
        origin = position;
    }

	public void initBehavior() {
	}

	public void performBehavior() {
		if (collisionDetected()) {
            // stop the robot
        	
        	rotateY(180);
//        	while(storeTime < 10000){
//            	setColor(new Color3f(255,0,0));
            setTranslationalVelocity(velocity);         
            setRotationalVelocity(0);
//                storeTime++;
//        	}

        } else {
        	
        	setColor(new Color3f(0,255,0));
        	
            // progress at 0.5 m/s
            setTranslationalVelocity(velocity);
            // frequently change orientation 
            if ((getCounter() % 100)==0) 
               setRotationalVelocity(Math.PI/2 * (0.5 - Math.random()));
        }

	}
	
	// Prompt to abort mission when an emergency occurs
	public void abort() {
		System.out.println("Robot: Aborting mission.");
		
		// Move back to starting position and stop moving.
        moveToStartPosition();
        setTranslationalVelocity(0.0);
        setRotationalVelocity(0);
	}
};
