// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

import RootElement.ClassDiagram.Package1.Coordinate;
import RootElement.ClassDiagram.Package1.Robot;

/************************************************************/
/**
 * 
 */
public class Robot_Picker extends Robot {
	/**
	 * 
	 */
	public RootElement.ClassDiagram.Integer objectsLeft = 30;

	/**
	 * 
	 * @param position 
	 * @param name  
	 */
	public void Robot_picker(Coordinate position, RootElement.ClassDiagram.String name) {
	}

	/**
	 * 
	 */
	public void initBehavior()() {
	}

	/**
	 * 
	 */
	public void performBehavior()() {
	}
};
