// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

import RootElement.ClassDiagram.Package1.Coordinate;
import RootElement.ClassDiagram.Package1.Robot;

/************************************************************/
/**
 * 
 */
public class Robot_Bumper extends Robot {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 * @param name 
	 * @param position 
	 */
	public void Robot_Bumper(RootElement.ClassDiagram.String name, Coordinate position) {
	}

	/**
	 * 
	 */
	public void initBehavior() {
	}

	/**
	 * 
	 */
	public void initBehavior() {
	}

	/**
	 * 
	 */
	public void bump() {
	}

	/**
	 * 
	 */
	public void performBehavior() {
	}
};
