// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.ClassDiagram.Package1;

/************************************************************/
/**
 * 
 */
public class Robot {
	/**
	 * 
	 */
	public RootElement.ClassDiagram.Real velocity;
	/**
	 * 
	 */
	public RootElement.ClassDiagram.Real rotation;
	/**
	 * 
	 */
	public RootElement.ClassDiagram.Real storeTime;

	/**
	 * 
	 */
	public void Robot() {
	}

	/**
	 * 
	 */
	public void initBehavior() {
	}

	/**
	 * 
	 */
	public void performBehavior() {
	}
};
